
const express=require("express"),cors=require("cors"),axios=require("axios"),{createClient}=require("@supabase/supabase-js");
const app=express();app.use(cors());app.use(express.json());
const sb=createClient("https://qqnhqtnkkzxnzcclzzvt.supabase.co","sb_publishable_LmDKIprQByu0Obl7kG6R7Q_-ZsOrElK");
const PK=process.env.PESAPAL_KEY||"bERTg3ACJMYAo8TQvGTcDyy+2eXbF0b2",PS=process.env.PESAPAL_SECRET||"jRa27BcmlflF61R+x3ngQ1e0dNg=",FLW=process.env.FLW_SECRET||"YOUR_FLW_KEY",WEB=process.env.WEBSITE_URL||"https://yourdomain.com",API=process.env.BACKEND_URL||"https://bweb-backend-production.up.railway.app",C=0.10,S=0.90;
app.get("/",(q,r)=>r.json({status:"✅ BWEB LIVE!"}));
app.post("/place-order",async(q,r)=>{try{const{buyer_name,buyer_email,buyer_phone,seller_id,seller_name,seller_phone,product_id,product_name,product_emoji,quantity,unit_price,order_type,delivery_address,notes,payment_method}=q.body;if(!buyer_email||!product_id||!quantity||!unit_price)return r.status(400).json({error:"Missing fields"});const t=parseFloat(unit_price)parseInt(quantity),cm=+(tC).toFixed(2),sa=+(tS).toFixed(2);const{data:o,error}=await sb.from("orders").insert([{buyer_name,buyer_email,buyer_phone,seller_id,seller_name,seller_phone,product_id,product_name,product_emoji:product_emoji||"📦",quantity:parseInt(quantity),unit_price:parseFloat(unit_price),total_amount:t,commission:cm,seller_amount:sa,order_type:order_type||"unique",delivery_address:delivery_address||"",notes:notes||"",payment_method,status:"pending",payment_status:"unpaid",delivery_confirmed:false,seller_paid:false}]).select().single();if(error)throw error;await sb.from("commissions").insert([{order_id:o.id,total_amount:t,commission:cm,seller_amount:sa,status:"pending"}]);return r.json({success:true,order_id:o.id,total_amount:t,commission:cm,seller_amount:sa})}catch(e){return r.status(500).json({error:"Failed"})}});
app.post("/pay/pesapal",async(q,r)=>{try{const{order_id}=q.body;const{data:o}=await sb.from("orders").select("").eq("id",order_id).single();if(!o)return r.status(404).json({error:"Not found"});const a=await axios.post("https://cybqa.pesapal.com/pesapalv3/api/Auth/RequestToken",{consumer_key:PK,consumer_secret:PS},{headers:{"Content-Type":"application/json",Accept:"application/json"}});const tk=a.data?.token;if(!tk)return r.status(500).json({error:"Auth failed"});const ip=await axios.post("https://cybqa.pesapal.com/pesapalv3/api/URLSetup/RegisterIPN",{url:${API}/webhook/pesapal,ipn_notification_type:"POST"},{headers:{Authorization:Bearer ${tk},"Content-Type":"application/json"}});const sb2=await axios.post("https://cybqa.pesapal.com/pesapalv3/api/Transactions/SubmitOrderRequest",{id:order_id,currency:"USD",amount:o.total_amount,description:BWEB:${o.product_name},callback_url:${API}/payment-callback?order_id=${order_id},notification_id:ip.data?.ipn_id,billing_address:{email_address:o.buyer_email,phone_number:o.buyer_phone||"",first_name:o.buyer_name?.split(" ")[0]||"Buyer",last_name:""}},{headers:{Authorization:Bearer ${tk},"Content-Type":"application/json"}});const pu=sb2.data?.redirect_url;if(!pu)return r.status(500).json({error:"Failed"});return r.json({success:true,payment_url:pu})}catch(e){return r.status(500).json({error:"PesaPal failed"})}});
app.post("/pay/flutterwave",async(q,r)=>{try{const{order_id}=q.body;const{data:o}=await sb.from("orders").select("").eq("id",order_id).single();if(!o)return r.status(404).json({error:"Not found"});const tx=BWEB-${order_id}-${Date.now()};const fw=await axios.post("https://api.flutterwave.com/v3/payments",{tx_ref:tx,amount:o.total_amount,currency:"USD",redirect_url:${API}/payment-callback?order_id=${order_id},customer:{email:o.buyer_email,phonenumber:o.buyer_phone||"",name:o.buyer_name||"Buyer"},customizations:{title:"BWEB Industries",description:o.product_name},meta:{order_id}},{headers:{Authorization:Bearer ${FLW},"Content-Type":"application/json"}});const pu=fw.data?.data?.link;if(!pu)return r.status(500).json({error:"Failed"});return r.json({success:true,payment_url:pu})}catch(e){return r.status(500).json({error:"Flutterwave failed"})}});
async function markPaid(id,m){const{data:o}=await sb.from("orders").select("").eq("id",id).single();if(!o||o.payment_status==="paid")return;await sb.from("orders").update({payment_status:"paid",status:"paid"}).eq("id",id);await sb.from("commissions").update({status:"collected"}).eq("order_id",id);await sb.from("notifications").insert([{user_id:o.seller_id,type:"new_order",title:"🛒 New Order!",message:${o.buyer_name} ordered ${o.product_name}. Get $${o.seller_amount} after delivery.,order_id:id,read:false},{user_id:o.buyer_email,type:"paid",title:"✅ Payment Confirmed!",message:$${o.total_amount} received for ${o.product_name}!,order_id:id,read:false}]);}
app.post("/webhook/pesapal",async(q,r)=>{try{await markPaid(q.body.OrderMerchantReference,"pesapal");r.send("OK")}catch{r.send("Error")}});
app.post("/webhook/flutterwave",async(q,r)=>{try{const e=q.body;if(e.event==="charge.completed"&&e.data?.status==="successful")await markPaid(e.data?.meta?.order_id,"flutterwave");r.send("OK")}catch{r.send("Error")}});
app.get("/payment-callback",async(q,r)=>{const{order_id}=q.query;const{data:o}=await sb.from("orders").select("payment_status").eq("id",order_id).single();r.redirect(o?.payment_status==="paid"?${WEB}?success=1&order_id=${order_id}:${WEB}?failed=1)});
app.post("/update-status",async(q,r)=>{try{const{order_id,seller_id,new_status}=q.body;const{data:o}=await sb.from("orders").select("").eq("id",order_id).single();if(!o)return r.status(404).json({error:"Not found"});if(o.seller_id!==seller_id)return r.status(403).json({error:"Not yours"});await sb.from("orders").update({status:new_status}).eq("id",order_id);await sb.from("notifications").insert([{user_id:o.buyer_email,type:"update",title:"📦 Order Update!",message:${o.product_name} is ${new_status}!,order_id,read:false}]);return r.json({success:true})}catch(e){return r.status(500).json({error:"Failed"})}});
app.post("/confirm-delivery",async(q,r)=>{try{const{order_id,buyer_email}=q.body;const{data:o}=await sb.from("orders").select("").eq("id",order_id).single();if(!o)return r.status(404).json({error:"Not found"});if(o.buyer_email!==buyer_email)return r.status(403).json({error:"Not yours"});if(o.delivery_confirmed)return r.status(400).json({error:"Already done"});await sb.from("orders").update({delivery_confirmed:true,status:"delivered"}).eq("id",order_id);await sb.from("payouts").insert([{order_id,seller_id:o.seller_id,seller_name:o.seller_name,product_name:o.product_name,amount:o.seller_amount,commission:o.commission,total_order:o.total_amount,status:"pending"}]);await sb.from("commissions").update({status:"finalized"}).eq("order_id",order_id);await sb.from("notifications").insert([{user_id:o.seller_id,type:"payout",title:"💰 Payout Coming!",message:$${o.seller_amount} coming for ${o.product_name}!,order_id,read:false}]);return r.json({success:true,seller_payout:o.seller_amount,bweb_commission:o.commission})}catch(e){return r.status(500).json({error:"Failed"})}});
app.get("/orders/buyer",async(q,r)=>{const{email}=q.query;const{data:o}=await sb.from("orders").select("").eq("buyer_email",email).order("created_at",{ascending:false});r.json({success:true,orders:o||[]})});
app.get("/orders/seller",async(q,r)=>{const{seller_id}=q.query;const{data:o}=await sb.from("orders").select("").eq("seller_id",seller_id).order("created_at",{ascending:false});const orders=o||[];r.json({success:true,orders,stats:{total_orders:orders.length,total_revenue:orders.filter(x=>x.delivery_confirmed).reduce((s,x)=>s+x.seller_amount,0),pending_payout:orders.filter(x=>x.payment_status==="paid"&&!x.delivery_confirmed).reduce((s,x)=>s+x.seller_amount,0)}})});
app.get("/notifications",async(q,r)=>{const{user_id}=q.query;const{data:n}=await sb.from("notifications").select("").eq("user_id",user_id).order("created_at",{ascending:false}).limit(30);const notifs=n||[];r.json({success:true,notifications:notifs,unread:notifs.filter(x=>!x.read).length})});
app.get("/admin/commissions",async(q,r)=>{if(q.query.key!==process.env.ADMIN_KEY)return r.status(403).json({error:"Unauthorized"});const{data:c}=await sb.from("commissions").select("");const cc=c||[];r.json({success:true,total_earned:cc.filter(x=>x.status==="finalized").reduce((s,x)=>s+(x.commission||0),0),commissions:cc})});
app.post("/ai/assistant",async(q,r)=>{try{const{message,role,location,seller_id}=q.body;if(!message)return r.status(400).json({error:"Required"});const{data:p}=await sb.from("products").select("name,price,country,county,seller_name,emoji").limit(50);const list=(p||[]).map(x=>${x.emoji}${x.name} $${x.price}|${x.seller_name}|${x.county},${x.country}).join("\n");const roles={buyer:"Help BUYER find products.",seller:"Help SELLER grow business. BWEB=10%, seller=90%.",admin:"Help ADMIN with strategy."};const ai=await axios.post("https://api.anthropic.com/v1/messages",{model:"claude-3-haiku-20240307",max_tokens:500,system:BWEB AI. ${roles[role]||roles.buyer} Location:${location||"?"}\nProducts:\n${list||"None yet"},messages:[{role:"user",content:message}]},{headers:{"x-api-key":process.env.ANTHROPIC_KEY,"anthropic-version":"2023-06-01","Content-Type":"application/json"}});return r.json({success:true,reply:ai.data?.content?.[0]?.text||"Try again!"})}catch(e){return r.status(500).json({reply:"AI unavailable!"})}});
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(✅ BWEB running on port ${PORT}));
    
